# Site settings
title: Curt's site
description: Welcome to my world
baseurl: "/" # the subpath of your site, e.g. /blog
#url: "https://varjo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://localhost:3000"
#resource: "https://varjo.github.io/"
resource: "http://localhost:3000/"

# User settings
username: Curt
user_description: Hax
user_title: Title
email: email@email.com
twitter_username: twitter_name
github_username: github_name
gplus_username:  google_name

# Google-analytics
google-analytics:
  id: "iG-XF2FHSNQSJ"

exclude: ['package.json', 'src' , 'node_modules']
